import type { AcademyInfoResponse } from "@/features/academy/type";
import type { Asset, AssetApplication } from "@/features/asset/type";

export const MOCK_ACADEMY_INFO: AcademyInfoResponse = {
  basicInfo: {
    academyName: "KOSTA 가산교육센터",
    representativeName: "이민하",
    representativePhone: "053-323-5225",
    businessNumber: "ACA-2023-9981",
    address: "서울특별시 구로구 디지털로 20길 10 스테이린 203호",
  },
  overview: {
    totalStudents: 1240,
    totalEnrolled: 85,
    usageRate: 45,
  },
  branches: [
    { id: 1, branchName: "KOSTA 가산교육센터", manager: "드웨인 신데렐라", status: "active" },
    { id: 2, branchName: "KOSTA 대구교육센터", manager: "박정희",          status: "active" },
  ],
};

export const MOCK_ASSETS: Asset[] = [
  {
    id: "asset-1",
    categoryName: "교재",
    categoryId: "cat-1",
    name: "수학 문제집",
    stock: 40,
    vendorName: "대한출판",
    vendorId: "vendor-1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "asset-2",
    categoryName: "비품",
    categoryId: "cat-2",
    name: "A4용지",
    stock: 100,
    vendorName: "오피스마트",
    vendorId: "vendor-2",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "asset-3",
    categoryName: "비품",
    categoryId: "cat-2",
    name: "프린트 토너",
    stock: 5,
    vendorName: "오피스마트",
    vendorId: "vendor-2",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
];

export const MOCK_ASSET_APPLICATIONS: AssetApplication[] = [
  {
    id: "app-1",
    userName: "김길동",
    userId: "user-1",
    categoryName: "교재",
    categoryId: "cat-1",
    vendorName: "대한출판",
    vendorId: "vendor-1",
    assetId: "asset-1",
    assetName: "수학 문제집",
    quantity: 10,
    price: 120000,
    reason: "수업 교재 보충",
    status: "PENDING",
    requestedAt: new Date("2024-10-24"),
  },
  {
    id: "app-2",
    userName: "이순자",
    userId: "user-2",
    categoryName: "비품",
    categoryId: "cat-2",
    vendorName: "오피스마트",
    vendorId: "vendor-2",
    assetId: "asset-2",
    assetName: "A4용지",
    quantity: 5,
    price: 25000,
    reason: "사무용품 보충",
    status: "ACCEPTED",
    requestedAt: new Date("2024-10-23"),
    processedAt: new Date("2024-10-24"),
  },
  {
    id: "app-3",
    userName: "박지현",
    userId: "user-3",
    categoryName: "비품",
    categoryId: "cat-2",
    vendorName: "오피스마트",
    vendorId: "vendor-2",
    assetId: "asset-3",
    assetName: "프린트 토너",
    quantity: 2,
    price: 60000,
    reason: "토너 교체 필요",
    rejectedReason: "예산 초과",
    status: "REJECTED",
    requestedAt: new Date("2024-10-20"),
    processedAt: new Date("2024-10-21"),
  },
];